using System;
using UnityEngine;

namespace FrameAction
{
    public enum FrameActionMatterCarrier
    {
        Rigid,
        Liquid,
        Gas,
    }

    /// <summary>
    /// Project-agnostic authoring metadata emitted by SpriteCue maps. The consuming game owns
    /// material simulation, reactions and presentation; SpriteCue Runtime only preserves the
    /// authored carrier, element and geometry in map-local world units.
    /// </summary>
    [DisallowMultipleComponent]
    public sealed class FrameActionElementMatterSource2D : MonoBehaviour
    {
        public string sourceId;
        public FrameActionMatterCarrier carrier;
        [Tooltip("Free-form identity interpreted by the consuming game, for example water or ice.")]
        public string elementTag;
        [Obsolete("Legacy load-only field. Use elementTag.")]
        public string element = "water";
        public FrameActionMatterVisualProfile2D visual = new FrameActionMatterVisualProfile2D();
        public FrameActionMatterPhysicalProfile2D physical = new FrameActionMatterPhysicalProfile2D();
        [Min(0f)] public float radiusWorldUnits = 0.1f;
        public Vector2[] localPoints = System.Array.Empty<Vector2>();
        [HideInInspector] public bool autoGeneratedRigidContour;

        public string EffectiveElementTag => !string.IsNullOrWhiteSpace(elementTag)
            ? elementTag.Trim()
            : element?.Trim() ?? string.Empty;
    }

    [Serializable]
    public sealed class FrameActionMatterVisualProfile2D
    {
        public Color baseColor = new Color(0.267f, 0.682f, 0.91f, 1f);
        public Color secondaryColor = new Color(0.267f, 0.682f, 0.91f, 1f);
        public Color emissionColor = Color.black;
        [Range(0f, 1f)] public float opacity = 0.78f;
        [Range(0.1f, 4f)] public float particleScale = 1f;
        [Range(0f, 1f)] public float edgeSoftness = 0.28f;
        [Range(0.1f, 8f)] public float detailScale = 1f;
        [Range(0f, 1f)] public float refractionStrength = 0.12f;
        [Range(0f, 8f)] public float glowStrength;
        [Range(0f, 1f)] public float foamAmount = 0.08f;
    }

    [Serializable]
    public sealed class FrameActionMatterPhysicalProfile2D
    {
        [Min(0.001f)] public float density = 1f;
        [Range(0f, 8f)] public float viscosity = 0.18f;
        [Range(0f, 4f)] public float surfaceTension = 0.34f;
        [Range(0.05f, 8f)] public float flowSpeed = 1f;
        [Range(-4f, 4f)] public float gravityScale = 1f;
        [Range(0f, 4f)] public float diffusion = 0.02f;
        [Range(-4f, 4f)] public float buoyancy;
        [Range(0f, 8f)] public float drag = 0.04f;
        [Min(0f)] public float evaporationHalfLifeSeconds = 1200f;
        [Min(0f)] public float dissipationHalfLifeSeconds;
    }
}
